In [1]:
!pip install polars
!pip install seaborn
!pip install pyarrow

Requirement already satisfied: polars in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (1.34.0)
Requirement already satisfied: polars-runtime-32==1.34.0 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from polars) (1.34.0)

WARNING: Ignoring invalid distribution ~oogle-ai-generativelanguage (C:\Users\T14\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~oogle-ai-generativelanguage (C:\Users\T14\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~oogle-ai-generativelanguage (C:\Users\T14\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (3.9.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.0)
Requirement already satisfied: pillow>=8 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)

WARNING: Ignoring invalid distribution ~oogle-ai-generativelanguage (C:\Users\T14\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~oogle-ai-generativelanguage (C:\Users\T14\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~oogle-ai-generativelanguage (C:\Users\T14\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pyarrow in c:\users\t14\appdata\local\programs\python\python311\lib\site-packages (21.0.0)

WARNING: Ignoring invalid distribution ~oogle-ai-generativelanguage (C:\Users\T14\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~oogle-ai-generativelanguage (C:\Users\T14\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~oogle-ai-generativelanguage (C:\Users\T14\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import os
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
def read_parquet_by_type(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    user_chunk_files = [file for file in files if 'user_chunk' in file]
    purchase_history_chunk_files = [file for file in files if 'purchase_history_daily_chunk' in file]
    item_chunk_files = [file for file in files if 'item_chunk' in file]
    
    # Đọc các file riêng biệt thành DataFrame
    user_chunk_df = pl.concat([pl.read_parquet(file) for file in user_chunk_files]) if user_chunk_files else None
    purchase_history_chunk_df = pl.concat([pl.read_parquet(file) for file in purchase_history_chunk_files]) if purchase_history_chunk_files else None
    item_chunk_df = pl.concat([pl.read_parquet(file) for file in item_chunk_files]) if item_chunk_files else None
    
    # Trả về một dictionary chứa các DataFrame
    return {
        "user_chunk": user_chunk_df,
        "purchase_history_chunk": purchase_history_chunk_df,
        "item_chunk": item_chunk_df
    }

In [3]:
train_path = '/datastore/uittogether2/LuuTru/Thanhhn/datasets/recommendation_dataset'
dataframes = read_parquet_by_type(train_path)

In [66]:
df_user = dataframes["user_chunk"]
df_purchase = dataframes["purchase_history_chunk"]
df_item = dataframes["item_chunk"]

# Head information of each Chunk

In [5]:
print("User Chunk DataFrame:")
df_user.head()

User Chunk DataFrame:

shape: (5, 18)
┌────────────┬────────┬──────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ customer_i ┆ gender ┆ location ┆ province   ┆ … ┆ install_da ┆ district  ┆ user_id   ┆ is_delete │
│ d          ┆ ---    ┆ ---      ┆ ---        ┆   ┆ te         ┆ ---       ┆ ---       ┆ d         │
│ ---        ┆ str    ┆ i32      ┆ str        ┆   ┆ ---        ┆ str       ┆ str       ┆ ---       │
│ i32        ┆        ┆          ┆            ┆   ┆ i64        ┆           ┆           ┆ bool      │
╞════════════╪════════╪══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 8307982    ┆ Nữ     ┆ 1177     ┆ Khánh Hòa  ┆ … ┆ 1738454400 ┆ Ninh Hòa  ┆ 90e7a2dea ┆ false     │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ bb8f1408a ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ e1d2500ba ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ c38…      ┆           │
│ 8307983    ┆ Nữ     ┆ 800      ┆ Đà Nẵng    ┆ … ┆ 1738454400 ┆ Hòa Vang  ┆ bcf5c9622 ┆ false     │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ 99e13948a ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ 5f00ec5ec ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ 8b9…      ┆           │
│ 8307984    ┆ Nam    ┆ 465      ┆ Long An    ┆ … ┆ 1738454400 ┆ Đức Hòa   ┆ f64e5fe63 ┆ false     │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ 6c027a62c ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ fc1e39738 ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ 6aa…      ┆           │
│ 8307985    ┆ Nữ     ┆ 716      ┆ Bình Dương ┆ … ┆ 1738454400 ┆ Tân Uyên  ┆ 367d4d382 ┆ false     │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ 8bc57a12c ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ 4ea52a428 ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ 955…      ┆           │
│ 8307986    ┆ Nữ     ┆ 320      ┆ Đồng Nai   ┆ … ┆ 1738454400 ┆ Định Quán ┆ 569c3c9fa ┆ false     │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ cccff404f ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ aa5904d14 ┆           │
│            ┆        ┆          ┆            ┆   ┆            ┆           ┆ 7be…      ┆           │
└────────────┴────────┴──────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [6]:
print("Purchase Chunk DataFrame:")
df_purchase.head()

Purchase Chunk DataFrame:

shape: (5, 16)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ timestamp  ┆ user_id   ┆ item_id   ┆ event_typ ┆ … ┆ payment  ┆ location ┆ discount  ┆ is_delete │
│ ---        ┆ ---       ┆ ---       ┆ e         ┆   ┆ ---      ┆ ---      ┆ ---       ┆ d         │
│ i64        ┆ str       ┆ str       ┆ ---       ┆   ┆ str      ┆ i32      ┆ decimal[3 ┆ ---       │
│            ┆           ┆           ┆ str       ┆   ┆          ┆          ┆ 8,4]      ┆ bool      │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ 1717185910 ┆ e9dd339da ┆ 684700000 ┆ Purchase  ┆ … ┆ VietQR   ┆ 687      ┆ 0.0000    ┆ false     │
│            ┆ f179ce867 ┆ 0002      ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ 16f0ce734 ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ e1d…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 1717182347 ┆ 76eeb2afc ┆ 137100000 ┆ Purchase  ┆ … ┆ Tiền mặt ┆ 340      ┆ 5000.0000 ┆ false     │
│            ┆ a779fba0b ┆ 0005      ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ d988a8910 ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ 074…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 1717184923 ┆ 52c68eecb ┆ 676700000 ┆ Purchase  ┆ … ┆ Tiền mặt ┆ 105      ┆ 20000.000 ┆ false     │
│            ┆ 3ca8241d1 ┆ 0002      ┆           ┆   ┆          ┆          ┆ 0         ┆           │
│            ┆ 04867d963 ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ 616…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 1717096117 ┆ 33a6209df ┆ 437300000 ┆ Purchase  ┆ … ┆ VNPay    ┆ 103      ┆ 0.0000    ┆ false     │
│            ┆ 085b3340d ┆ 0001      ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ 77160abe4 ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ 599…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 1717186942 ┆ 49ff16349 ┆ 388000000 ┆ Purchase  ┆ … ┆ Tiền mặt ┆ 127      ┆ 30000.000 ┆ false     │
│            ┆ 5595f68a3 ┆ 0001      ┆           ┆   ┆          ┆          ┆ 0         ┆           │
│            ┆ 839a2a292 ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ 963…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

In [7]:
print("User Item DataFrame:")
df_item.head()

User Item DataFrame:

shape: (5, 34)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ p_id  ┆ item_id    ┆ price      ┆ category_l ┆ … ┆ volume    ┆ material  ┆ sale_stat ┆ descripti │
│ ---   ┆ ---        ┆ ---        ┆ 1_id       ┆   ┆ ---       ┆ ---       ┆ us        ┆ on_new    │
│ i32   ┆ str        ┆ decimal[38 ┆ ---        ┆   ┆ str       ┆ str       ┆ ---       ┆ ---       │
│       ┆            ┆ ,4]        ┆ i32        ┆   ┆           ┆           ┆ i32       ┆ str       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 17065 ┆ 0502020000 ┆ 99000.0000 ┆ 1          ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Chi tiết  │
│       ┆ 004        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ …         │
│ 72370 ┆ 0010290040 ┆ 69000.0000 ┆ 3292       ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Không xác │
│       ┆ 150        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ định      │
│ 31154 ┆ 0008010000 ┆ 45000.0000 ┆ 351        ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Chi tiết  │
│       ┆ 015        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ …         │
│ 46123 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ Không xác ┆ Giấy, bột ┆ 0         ┆ Không xác │
│       ┆ 094        ┆ 0          ┆            ┆   ┆ định      ┆ giấy, vải ┆           ┆ định      │
│       ┆            ┆            ┆            ┆   ┆           ┆ không     ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ dệt,…     ┆           ┆           │
│ 46127 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ Không xác ┆ Giấy, bột ┆ 0         ┆ Không xác │
│       ┆ 098        ┆ 0          ┆            ┆   ┆ định      ┆ giấy, vải ┆           ┆ định      │
│       ┆            ┆            ┆            ┆   ┆           ┆ không     ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ dệt,…     ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Task 2.1A Xác Định Các Cặp Sản Phẩm Hay Mua Chung

In [8]:
# import polars as pl
# from itertools import combinations
# from collections import Counter

# # Giả sử bạn có df_purchase là Polars DataFrame
# # df_purchase = pl.read_parquet("purchases.parquet")

# # 1️⃣ Chuyển mỗi customer_id sang list sản phẩm mua
# group_col = "customer_id"
# df_grouped = (
#     df_purchase
#     .group_by(group_col)
#     .agg(pl.col("item_id").unique().alias("items"))
# )

# # 2️⃣ Đếm số lần xuất hiện cặp sản phẩm
# cooc_counter = Counter()

# for items in df_grouped["items"]:
#     if len(items) > 1:
#         for pair in combinations(sorted(items), 2):
#             cooc_counter[pair] += 1

# # 3️⃣ Tạo Polars DataFrame kết quả
# df_cooc = pl.DataFrame({
#     "item_1": [i1 for (i1, i2) in cooc_counter.keys()],
#     "item_2": [i2 for (i1, i2) in cooc_counter.keys()],
#     "cooc_count": list(cooc_counter.values())
# }).sort("cooc_count", descending=True)

# # 4️⃣ Hiển thị kết quả
# print(df_cooc.head(10))

In [14]:
print(df_purchase['created_date'])

shape: (35_729_825,)
Series: 'created_date' [datetime[μs]]
[
	2024-05-31 20:05:10.663
	2024-05-31 19:05:47.590
	2024-05-31 19:48:43.330
	2024-05-30 19:08:37.647
	2024-05-31 20:22:22.583
	…
	2024-10-05 12:16:43.507
	2024-10-05 08:48:41.620
	2024-10-05 17:00:07.040
	2024-10-05 13:29:59.503
	2024-10-05 18:35:01.133
]

In [ ]:
import polars as pl
from itertools import combinations
from collections import Counter

# --- Giả sử df_purchase có cột: customer_id, invoice_id, item_id ---
# df_purchase = pl.read_parquet("purchases.parquet")

# 1️⃣ Gom các sản phẩm trong cùng một hóa đơn
df_grouped = (
    df_purchase.group_by(["customer_id", "created_date"])
    .agg(pl.col("item_id").unique().alias("items"))
)

# 2️⃣ Đếm số lần xuất hiện cặp sản phẩm
cooc_counter = Counter()
for items in df_grouped["items"]:
    if len(items) > 1:
        for pair in combinations(sorted(items), 2):
            cooc_counter[pair] += 1

# 3️⃣ Kết quả
df_cooc = pl.DataFrame({
    "item_1": [i1 for (i1, i2) in cooc_counter.keys()],
    "item_2": [i2 for (i1, i2) in cooc_counter.keys()],
    "cooc_count": list(cooc_counter.values())
}).sort("cooc_count", descending=True)

print(df_cooc.head(10))

shape: (10, 3)
┌───────────────┬───────────────┬────────────┐
│ item_1        ┆ item_2        ┆ cooc_count │
│ ---           ┆ ---           ┆ ---        │
│ str           ┆ str           ┆ i64        │
╞═══════════════╪═══════════════╪════════════╡
│ 2803000000011 ┆ 2803000000013 ┆ 78235      │
│ 2803000000012 ┆ 2803000000013 ┆ 53478      │
│ 2803000000011 ┆ 2803000000012 ┆ 52843      │
│ 2803000000010 ┆ 2803000000012 ┆ 34204      │
│ 2803000000010 ┆ 2803000000013 ┆ 32656      │
│ 1371000000001 ┆ 1371000000002 ┆ 29677      │
│ 3880000000001 ┆ 3880000000002 ┆ 27793      │
│ 2803000000010 ┆ 2803000000011 ┆ 26985      │
│ 1371000000003 ┆ 1371000000006 ┆ 26776      │
│ 0029250010001 ┆ 0029250010003 ┆ 26509      │
└───────────────┴───────────────┴────────────┘

In [9]:
# Giả sử df_item chứa thông tin item_id, brand, category
brand_map = dict(zip(df_item["item_id"], df_item["brand"]))
cate_map = dict(zip(df_item["item_id"], df_item["category"]))

df_cooc_info = df_cooc.with_columns([
    pl.col("item_1").replace(brand_map).alias("brand_1"),
    pl.col("item_1").replace(cate_map).alias("category_1"),
    pl.col("item_2").replace(brand_map).alias("brand_2"),
    pl.col("item_2").replace(cate_map).alias("category_2")
])

print(df_cooc_info.head(10))

shape: (10, 7)
┌───────────────┬───────────────┬────────────┬─────────┬────────────┬─────────┬────────────┐
│ item_1        ┆ item_2        ┆ cooc_count ┆ brand_1 ┆ category_1 ┆ brand_2 ┆ category_2 │
│ ---           ┆ ---           ┆ ---        ┆ ---     ┆ ---        ┆ ---     ┆ ---        │
│ str           ┆ str           ┆ i64        ┆ str     ┆ str        ┆ str     ┆ str        │
╞═══════════════╪═══════════════╪════════════╪═════════╪════════════╪═════════╪════════════╡
│ 2803000000011 ┆ 2803000000013 ┆ 78235      ┆ HOFF    ┆ Hoff       ┆ HOFF    ┆ Hoff       │
│ 2803000000012 ┆ 2803000000013 ┆ 53478      ┆ HOFF    ┆ Hoff       ┆ HOFF    ┆ Hoff       │
│ 2803000000011 ┆ 2803000000012 ┆ 52843      ┆ HOFF    ┆ Hoff       ┆ HOFF    ┆ Hoff       │
│ 2803000000010 ┆ 2803000000012 ┆ 34204      ┆ HOFF    ┆ Hoff       ┆ HOFF    ┆ Hoff       │
│ 2803000000010 ┆ 2803000000013 ┆ 32656      ┆ HOFF    ┆ Hoff       ┆ HOFF    ┆ Hoff       │
│ 1371000000001 ┆ 1371000000002 ┆ 29677      ┆ Cây Thị ┆ Cây Thị    ┆ Cây Thị ┆ Cây Thị    │
│ 3880000000001 ┆ 3880000000002 ┆ 27793      ┆ HOFF    ┆ Hoff       ┆ HOFF    ┆ Hoff       │
│ 2803000000010 ┆ 2803000000011 ┆ 26985      ┆ HOFF    ┆ Hoff       ┆ HOFF    ┆ Hoff       │
│ 1371000000003 ┆ 1371000000006 ┆ 26776      ┆ Cây Thị ┆ Cây Thị    ┆ Cây Thị ┆ Cây Thị    │
│ 0029250010001 ┆ 0029250010003 ┆ 26509      ┆ Ivenet  ┆ Ivenet     ┆ Ivenet  ┆ Ivenet     │
└───────────────┴───────────────┴────────────┴─────────┴────────────┴─────────┴────────────┘

In [15]:
df_cooc_info_filter = df_cooc_info.filter(
    (pl.col("brand_1") != pl.col("brand_2")) | 
    (pl.col("category_1") != pl.col("category_2"))
).sort("cooc_count", descending=True)

In [13]:
import pandas as pd
target_path = '/datastore/uittogether2/LuuTru/Thanhhn/05_C_Python_For_ML/Task_2.1_Important_Feature'
df_cooc_info.to_pandas().to_csv(f'{target_path}/df_cooc_info.csv', index=False)

In [18]:
df_cooc_info_filter.to_pandas().to_csv(f'{target_path}/cooc_info.csv', index=False)

In [ ]:
print(df_purchase.columns)
print(df_item.columns)
print(df_purchase.columns)

['timestamp', 'user_id', 'item_id', 'event_type', 'event_value', 'price', 'date_key', 'quantity', 'customer_id', 'created_date', 'updated_date', 'channel', 'payment', 'location', 'discount', 'is_deleted']
['p_id', 'item_id', 'price', 'category_l1_id', 'category_l1', 'category_l2_id', 'category_l2', 'category_l3_id', 'category_l3', 'category_id', 'category', 'description', 'brand', 'manufacturer', 'creation_timestamp', 'is_deleted', 'created_date', 'updated_date', 'sync_status_id', 'last_sync_date', 'sync_error_message', 'image_url', 'gender_target', 'age_group', 'item_type', 'gp', 'weight', 'color', 'size', 'origin', 'volume', 'material', 'sale_status', 'description_new']
['timestamp', 'user_id', 'item_id', 'event_type', 'event_value', 'price', 'date_key', 'quantity', 'customer_id', 'created_date', 'updated_date', 'channel', 'payment', 'location', 'discount', 'is_deleted']

In [19]:
print(df_item.shape)

(27332, 34)

In [21]:
df_item = df_item.with_columns(
    pl.lit([]).alias("top10_bought_together")
)

In [22]:
print(df_item.columns)

['p_id', 'item_id', 'price', 'category_l1_id', 'category_l1', 'category_l2_id', 'category_l2', 'category_l3_id', 'category_l3', 'category_id', 'category', 'description', 'brand', 'manufacturer', 'creation_timestamp', 'is_deleted', 'created_date', 'updated_date', 'sync_status_id', 'last_sync_date', 'sync_error_message', 'image_url', 'gender_target', 'age_group', 'item_type', 'gp', 'weight', 'color', 'size', 'origin', 'volume', 'material', 'sale_status', 'description_new', 'top10_bought_together']

In [ ]:
# Lọc và sắp xếp top-10 mỗi item_1
top_items = (
    df_cooc_info
    .sort(["item_1", "cooc_count"], descending=[False, True])  # Sort theo item_1 và cooc_count
    .group_by("item_1")
    .agg([
        pl.col("item_2").head(10).alias("top10_items"),  # Lấy top 10 item_2 theo cooc_count
        pl.col("brand_1").head(10).alias("top10_brands_1"),  # Lấy top 10 brand của item_1
        pl.col("category_1").head(10).alias("top10_categories_1"),  # Lấy top 10 category của item_1
        pl.col("brand_2").head(10).alias("top10_brands_2"),  # Lấy top 10 brand của item_2
        pl.col("category_2").head(10).alias("top10_categories_2")  # Lấy top 10 category của item_2
    ])
)

In [24]:
print(top_items.head())

shape: (5, 6)
┌───────────────┬────────────────┬────────────────┬────────────────┬───────────────┬───────────────┐
│ item_1        ┆ top10_items    ┆ top10_brands_1 ┆ top10_categori ┆ top10_brands_ ┆ top10_categor │
│ ---           ┆ ---            ┆ ---            ┆ es_1           ┆ 2             ┆ ies_2         │
│ str           ┆ list[str]      ┆ list[str]      ┆ ---            ┆ ---           ┆ ---           │
│               ┆                ┆                ┆ list[str]      ┆ list[str]     ┆ list[str]     │
╞═══════════════╪════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 0000280000019 ┆ ["138600000000 ┆ ["TOYO (Thái   ┆ ["Đồ chơi nhà  ┆ ["Green       ┆ ["Green       │
│               ┆ 8",            ┆ Lan)", "TOYO   ┆ tắm", "Đồ chơi ┆ Bird",        ┆ Babi", "Xe mô │
│               ┆ "20440000001…  ┆ (Thá…          ┆ n…             ┆ "Thương hiệu  ┆ hình/hoạ…     │
│               ┆                ┆                ┆                ┆ kh…           ┆               │
│ 0000280000048 ┆ ["394900000004 ┆ ["Tobby",      ┆ ["Bóng/lều     ┆ ["Animo",     ┆ ["Bộ bé gái   │
│               ┆ 9",            ┆ "Tobby", …     ┆ bóng",         ┆ "Huggies      ┆ Animo",       │
│               ┆ "22650000000…  ┆ "Tobby"]       ┆ "Bóng/lều bó…  ┆ Skincare", …  ┆ "Huggies T…   │
│ 0000280000050 ┆ ["204400000011 ┆ ["Tobby",      ┆ ["Bóng/lều     ┆ ["Thương hiệu ┆ ["Lắp ráp/Xếp │
│               ┆ 4",            ┆ "Tobby", …     ┆ bóng",         ┆ khác", "Green ┆ hình", "Green │
│               ┆ "13860000000…  ┆ "Tobby"]       ┆ "Bóng/lều bó…  ┆ Bi…           ┆ Ba…           │
│ 0000280000070 ┆ ["209100000001 ┆ ["Không xác    ┆ ["Đồ chơi xếp  ┆ ["TOYCITY",   ┆ ["Thú nhún    │
│               ┆ 5",            ┆ định", "Không  ┆ chồng/thả hình ┆ "Animo", …    ┆ kéo", "Giày   │
│               ┆ "37770000000…  ┆ xác …          ┆ k…             ┆ "Animo"…      ┆ và Sand…      │
│ 0000280000098 ┆ ["218800000002 ┆ ["Long Thủy",  ┆ ["Học tập",    ┆ ["Thương hiệu ┆ ["Học tập",   │
│               ┆ 8",            ┆ "Long Thủy"]   ┆ "Học tập"]     ┆ khác",        ┆ "Dưỡng da     │
│               ┆ "00073800000…  ┆                ┆                ┆ "Cetaphil…    ┆ Cetaphil…     │
└───────────────┴────────────────┴────────────────┴────────────────┴───────────────┴───────────────┘

In [34]:
df_cooc_swapped = (
    df_cooc_info
    .select([
        pl.col("item_2").alias("item_1"),  # Đảo ngược item_1 và item_2
        pl.col("item_1").alias("item_2"),
        pl.col("cooc_count"),
        pl.col("brand_2").alias("brand_1"),
        pl.col("category_2").alias("category_1"),
        pl.col("brand_1").alias("brand_2"),  # Đảo ngược brand
        pl.col("category_1").alias("category_2")  # Đảo ngược category
    ])
)

# 2) Kết hợp bảng gốc và bảng đảo ngược
df_cooc_combined = pl.concat([df_cooc_info, df_cooc_swapped])

In [36]:
df_cooc_combined_sorted = df_cooc_combined.sort(by="cooc_count", descending=True)

# Kiểm tra kết quả
print(df_cooc_combined_sorted)

shape: (14_833_716, 7)
┌───────────────┬───────────────┬────────────┬─────────┬───────────────┬───────────┬───────────────┐
│ item_1        ┆ item_2        ┆ cooc_count ┆ brand_1 ┆ category_1    ┆ brand_2   ┆ category_2    │
│ ---           ┆ ---           ┆ ---        ┆ ---     ┆ ---           ┆ ---       ┆ ---           │
│ str           ┆ str           ┆ i64        ┆ str     ┆ str           ┆ str       ┆ str           │
╞═══════════════╪═══════════════╪════════════╪═════════╪═══════════════╪═══════════╪═══════════════╡
│ 2803000000011 ┆ 2803000000013 ┆ 78235      ┆ HOFF    ┆ Hoff          ┆ HOFF      ┆ Hoff          │
│ 2803000000013 ┆ 2803000000011 ┆ 78235      ┆ HOFF    ┆ Hoff          ┆ HOFF      ┆ Hoff          │
│ 2803000000012 ┆ 2803000000013 ┆ 53478      ┆ HOFF    ┆ Hoff          ┆ HOFF      ┆ Hoff          │
│ 2803000000013 ┆ 2803000000012 ┆ 53478      ┆ HOFF    ┆ Hoff          ┆ HOFF      ┆ Hoff          │
│ 2803000000011 ┆ 2803000000012 ┆ 52843      ┆ HOFF    ┆ Hoff          ┆ HOFF      ┆ Hoff          │
│ …             ┆ …             ┆ …          ┆ …       ┆ …             ┆ …         ┆ …             │
│ 6048000000040 ┆ 5006000000009 ┆ 1          ┆ Animo   ┆ 0-12M         ┆ TAOKAENOI ┆ Tao Kae Noi   │
│               ┆               ┆            ┆         ┆ Bodysuit đông ┆           ┆               │
│               ┆               ┆            ┆         ┆ vải mỏng      ┆           ┆               │
│ 6049000000063 ┆ 5006000000009 ┆ 1          ┆ Animo   ┆ Áo ghile đông ┆ TAOKAENOI ┆ Tao Kae Noi   │
│ 6049000000063 ┆ 6048000000040 ┆ 1          ┆ Animo   ┆ Áo ghile đông ┆ Animo     ┆ 0-12M         │
│               ┆               ┆            ┆         ┆               ┆           ┆ Bodysuit đông │
│               ┆               ┆            ┆         ┆               ┆           ┆ vải mỏng      │
│ 1455000000003 ┆ 0019000000004 ┆ 1          ┆ US FOOD ┆ Ruốc          ┆ Autoru    ┆ Máy đưa võng  │
│ 7163000000002 ┆ 0019000000004 ┆ 1          ┆ Maeil   ┆ Maeil         ┆ Autoru    ┆ Máy đưa võng  │
└───────────────┴───────────────┴────────────┴─────────┴───────────────┴───────────┴───────────────┘

In [70]:
import polars as pl
from tqdm import tqdm  # Để hiển thị tiến độ

df_item_head = df_item.head()

# 1. Hàm lọc top-10 cho mỗi item_1
def filter_top_10_for_item(item_1, df_cooc_sorted):
    # Lọc các cặp item_1 với item_2
    item_pairs = df_cooc_sorted.filter(pl.col("item_1") == item_1)
    
    # Bước 1: Đảm bảo có tối đa 5 item giống nhau về brand hoặc category
    item_pairs_same = item_pairs.filter(
        (pl.col("brand_1") == pl.col("brand_2")) | (pl.col("category_1") == pl.col("category_2"))
    )
    
    # Bước 2: Đảm bảo có ít nhất 5 item khác nhau
    item_pairs_diff = item_pairs.filter(
        (pl.col("brand_1") != pl.col("brand_2")) & (pl.col("category_1") != pl.col("category_2"))
    )
    
    # Bước 3: Lấy top-10 items mua cùng (chọn số lượng khác nhau)
    top_items = item_pairs.select(
        [pl.col("item_2").head(10).alias("top10_items"), 
         pl.col("cooc_count").head(10).alias("top10_cooc_count")]
    )
    
    return top_items

# 2. Lọc và cập nhật cột top10_bought_together trong df_item
def update_top10(df_item, df_cooc_combined_sorted):
    # Khởi tạo cột top10_bought_together với kiểu List rỗng
    df_item = df_item.with_columns(
        pl.lit([]).cast(pl.List(pl.Utf8)).alias("top10_bought_together")  # Khởi tạo cột trống kiểu List
    )

    # Bước 1: Tạo top-10 items cho mỗi item_id trong df_item
    top_items_list = []

    # Duyệt qua từng item_id trong df_item và sử dụng tqdm để hiển thị tiến độ
    for item_id in tqdm(df_item["item_id"], desc="Updating top-10 items", unit="item"):
        top_items = filter_top_10_for_item(item_id, df_cooc_combined_sorted)
        
        # Lấy toàn bộ danh sách top-10 items (không dùng [0] để tránh "out of range")
        top_items_list.append(top_items["top10_items"].to_list())  # Lấy phần tử đầu tiên (danh sách top-10)

    # Bước 2: Tạo DataFrame top_items_df với top10_items cho mỗi item_id
    top_items_df = pl.DataFrame({
        "item_id": df_item["item_id"],  # Tạo cột item_id từ df_item
        "top10_bought_together": top_items_list  # Cột top10_bought_together từ top_items_list
    })

    # Bước 3: Join với df_item để cập nhật cột top10_bought_together trực tiếp
    df_item = df_item.join(top_items_df, on="item_id", how="left")  # Join trên item_id để lấy top10_bought_together

    return df_item

# Cập nhật cột top10_bought_together trong df_item
df_item = update_top10(df_item, df_cooc_combined_sorted)

# Kiểm tra kết quả
print(df_item.head(10))

Updating top-10 items: 100%|██████████| 27332/27332 [21:59<00:00, 20.71item/s]

shape: (10, 36)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ p_id  ┆ item_id    ┆ price      ┆ category_l ┆ … ┆ sale_stat ┆ descripti ┆ top10_bou ┆ top10_bou │
│ ---   ┆ ---        ┆ ---        ┆ 1_id       ┆   ┆ us        ┆ on_new    ┆ ght_toget ┆ ght_toget │
│ i32   ┆ str        ┆ decimal[38 ┆ ---        ┆   ┆ ---       ┆ ---       ┆ her       ┆ her_right │
│       ┆            ┆ ,4]        ┆ i32        ┆   ┆ i32       ┆ str       ┆ ---       ┆ ---       │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆ list[str] ┆ list[str] │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 17065 ┆ 0502020000 ┆ 99000.0000 ┆ 1          ┆ … ┆ 0         ┆ Chi tiết  ┆ []        ┆ ["0502020 │
│       ┆ 004        ┆            ┆            ┆   ┆           ┆ sản phẩm  ┆           ┆ 340085",  │
│       ┆            ┆            ┆            ┆   ┆           ┆ …         ┆           ┆ "13960000 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 000…      │
│ 72370 ┆ 0010290040 ┆ 69000.0000 ┆ 3292       ┆ … ┆ 0         ┆ Không xác ┆ []        ┆ []        │
│       ┆ 150        ┆            ┆            ┆   ┆           ┆ định      ┆           ┆           │
│ 31154 ┆ 0008010000 ┆ 45000.0000 ┆ 351        ┆ … ┆ 0         ┆ Chi tiết  ┆ []        ┆ ["0008170 │
│       ┆ 015        ┆            ┆            ┆   ┆           ┆ sản phẩm  ┆           ┆ 000235",  │
│       ┆            ┆            ┆            ┆   ┆           ┆ …         ┆           ┆ "51140000 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 000…      │
│ 46123 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ 0         ┆ Không xác ┆ []        ┆ ["5950000 │
│       ┆ 094        ┆ 0          ┆            ┆   ┆           ┆ định      ┆           ┆ 000001",  │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ "00200200 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 001…      │
│ 46127 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ 0         ┆ Không xác ┆ []        ┆ ["1512000 │
│       ┆ 098        ┆ 0          ┆            ┆   ┆           ┆ định      ┆           ┆ 000004",  │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ "00200200 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 001…      │
│ 79850 ┆ 0024181040 ┆ 49000.0000 ┆ 3292       ┆ … ┆ 0         ┆ Không xác ┆ []        ┆ []        │
│       ┆ 235        ┆            ┆            ┆   ┆           ┆ định      ┆           ┆           │
│ 49907 ┆ 0008180000 ┆ 425000.000 ┆ 351        ┆ … ┆ 0         ┆ Chi tiết  ┆ []        ┆ ["0008180 │
│       ┆ 017        ┆ 0          ┆            ┆   ┆           ┆ sản phẩm  ┆           ┆ 000018",  │
│       ┆            ┆            ┆            ┆   ┆           ┆ …         ┆           ┆ "00081800 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 000…      │
│ 49931 ┆ 0020010000 ┆ 355000.000 ┆ 2222       ┆ … ┆ 0         ┆ Không xác ┆ []        ┆ ["2393000 │
│       ┆ 150        ┆ 0          ┆            ┆   ┆           ┆ định      ┆           ┆ 000001",  │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ "27460000 │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ 000…      │
│ 26694 ┆ 0501030000 ┆ 69000.0000 ┆ 3292       ┆ … ┆ 0         ┆ null      ┆ []        ┆ []        │
│       ┆ 126        ┆            ┆            ┆   ┆           ┆           ┆           ┆           │
│ 50189 ┆ 0020010000 ┆ 379000.000 ┆ 2222       ┆ … ┆ 0         ┆ Chi tiết  ┆ []        ┆ []        │
│       ┆ 151        ┆ 0          ┆            ┆   ┆           ┆ sản phẩm  ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ …         ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [82]:
print(df_item['top10_bought_together_right'][0])

shape: (10,)
Series: '' [str]
[
	"0502020340085"
	"1396000000034"
	"1743000000004"
	"2707000000001"
	"2752000000003"
	"2766000000005"
	"4548000000003"
	"4553000000003"
	"4837000000001"
	"5358000000001"
]